INSERT INTO users_information.topic_list (topic_name,image_path) VALUES
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png"),
("DSA","assets/images_courses/web-development.png");
